apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: qa
  namespace: kostis-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kostis-demo
    sources:
      direct: true
  verification:
    analysisTemplates:
    - name: count-interval-example     
  promotionTemplate:
    spec:
      steps:
      - task:
          name: kostis-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging-us
  namespace: kostis-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kostis-demo
    sources:
      stages:
      - qa
  promotionTemplate:
    spec:
      steps:
      - task:
          name: kostis-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging-eu
  namespace: kostis-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kostis-demo
    sources:
      stages:
      - qa
  promotionTemplate:
    spec:
      steps:
      - task:
          name: kostis-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging-asia
  namespace: kostis-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kostis-demo
    sources:
      direct: true    
      stages:
      - qa
  promotionTemplate:
    spec:
      steps:
      - task:
          name: kostis-promo-process
        as: promo-process      
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: load-gpu
  namespace: kostis-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kostis-demo
    sources:
      direct: true
      stages:
      - staging-us
      - staging-eu
      - staging-asia
  verification:
    analysisTemplates:
    - name: count-interval-example        
  promotionTemplate:
    spec:
      steps:
      - task:
          name: kostis-promo-process
        as: promo-process                    
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-us
  namespace: kostis-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kostis-demo
    sources:
      stages:
      - load-gpu
  promotionTemplate:
    spec:
      steps:
      - task:
          name: kostis-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-asia
  namespace: kostis-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kostis-demo
    sources:
      stages:
      - load-gpu      
  promotionTemplate:
    spec:
      steps:
      - task:
          name: kostis-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eu
  namespace: kostis-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kostis-demo
    sources:
      stages:
      - load-gpu
  promotionTemplate:
    spec:
      steps:
      - task:
          name: kostis-promo-process
        as: promo-process                
